# Generated by Django 4.2.6 on 2023-10-13 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator, django.core.validators.MinLengthValidator(16)], verbose_name='email address')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)])),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('create_not_signup', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('customer', 'CUSTOMER')], default='CUSTOMER', max_length=30)),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
    ]
